/**
 * MemoryAdapter interface.
 *
 * The abstract contract for the memory subsystem. Lets you plug in any database
 * backend (SQLite, in-memory, or your own) behind one interface.
 *
 * @example
 * ```typescript
 * import { MemoryAdapter, initMemory } from './memory/index.js';
 *
 * class MyCustomAdapter implements MemoryAdapter {
 *   // implement all methods...
 * }
 *
 * initMemory(new MyCustomAdapter());
 * ```
 */

import {
  MessageRole,
  ConversationStatus,
  SearchOptions,
  KeywordSearchResult,
  VectorSearchResult,
  HybridSearchResult,
  HybridSearchOptions,
} from './types.js';

// ============================================================
// Adapter data types (no external package dependencies)
// ============================================================

/** Conversation data (adapter return shape). */
export interface ConversationData {
  id: string;
  /** Caller identity. Single-user defaults to 'local'. This is a SEAM — see src/cautionary/. */
  userId: string;
  title: string;
  createdAt: Date;
  updatedAt: Date;
  messageCount: number;
  status: ConversationStatus;
}

/** Message data (adapter return shape). */
export interface MessageData {
  id: string;
  role: MessageRole;
  content: string;
  timestamp: Date;
  embedding?: number[];
}

/** Message input (used when creating a new message). */
export interface MessageInput {
  role: MessageRole;
  content: string;
  /** Whether to generate an embedding for this message. */
  generateEmbedding?: boolean;
}

/** Conversation list item. */
export interface ConversationListItem {
  id: string;
  title: string;
  updatedAt: Date;
  messageCount: number;
  status?: ConversationStatus;
}

/** Generic memory search result. */
export interface MemorySearchResult {
  messageId: string;
  conversationId: string;
  content: string;
  role: MessageRole;
  score: number;
  timestamp: Date;
}

// ============================================================
// MemoryAdapter interface
// ============================================================

/**
 * MemoryAdapter interface.
 *
 * Every memory backend must implement this.
 */
export interface MemoryAdapter {
  // ==================== Conversation operations ====================

  /**
   * Create a new conversation.
   * @param userId User ID
   * @param title Conversation title (optional, auto-generated by default)
   * @returns Conversation ID
   */
  createConversation(userId: string, title?: string): Promise<string>;

  /**
   * Get conversation details.
   * @param conversationId Conversation ID
   * @returns Conversation data or null
   */
  getConversation(conversationId: string): Promise<ConversationData | null>;

  /**
   * Get a user's conversation list (paginated).
   * @param userId User ID
   * @param limit Max count (default 20)
   * @param offset Skip count (default 0)
   * @returns Conversation list
   */
  getUserConversations(userId: string, limit?: number, offset?: number): Promise<ConversationListItem[]>;

  /**
   * Update conversation title.
   * @param conversationId Conversation ID
   * @param title New title
   */
  updateTitle(conversationId: string, title: string): Promise<void>;

  /**
   * Delete a conversation (soft-delete recommended).
   * @param conversationId Conversation ID
   */
  deleteConversation(conversationId: string): Promise<void>;

  /**
   * Verify conversation ownership.
   * @param conversationId Conversation ID
   * @param userId User ID
   * @returns Whether the user owns the conversation
   */
  verifyOwnership(conversationId: string, userId: string): Promise<boolean>;

  // ==================== Message operations ====================

  /**
   * Add a message.
   * @param conversationId Conversation ID
   * @param message Message content
   * @returns Message ID
   */
  addMessage(conversationId: string, message: MessageInput): Promise<string>;

  /**
   * Get a conversation's message list.
   * @param conversationId Conversation ID
   * @param limit Max count (default 50)
   * @returns Message list
   */
  getMessages(conversationId: string, limit?: number): Promise<MessageData[]>;

  // ==================== Search (optional) ====================

  /**
   * Semantic search (optional).
   * @param userId User ID
   * @param query Search query
   * @param options Search options
   */
  search?(userId: string, query: string, options?: SearchOptions): Promise<MemorySearchResult[]>;

  /**
   * Keyword search (optional).
   * Pure text search via BM25 or FTS.
   * @param userId User ID
   * @param query Search query
   * @param options Search options
   */
  keywordSearch?(userId: string, query: string, options?: SearchOptions): Promise<KeywordSearchResult[]>;

  /**
   * Vector search (optional).
   * Pure vector similarity search.
   * @param userId User ID
   * @param query Search query
   * @param options Search options
   */
  vectorSearch?(userId: string, query: string, options?: SearchOptions): Promise<VectorSearchResult[]>;

  /**
   * Hybrid search (optional).
   * Combines vector and keyword search with a weighted merge.
   * @param userId User ID
   * @param query Search query
   * @param options Hybrid search options
   */
  hybridSearch?(userId: string, query: string, options?: HybridSearchOptions): Promise<HybridSearchResult[]>;
}

// ============================================================
// Adapter management
// ============================================================

/** The currently active adapter instance. */
let currentAdapter: MemoryAdapter | null = null;

/**
 * Initialize the memory system.
 *
 * @param adapter MemoryAdapter instance
 *
 * @example
 * ```typescript
 * import { initMemory, createSQLiteAdapter } from './memory/index.js';
 *
 * initMemory(createSQLiteAdapter({ dbPath: './data/memory.db' }));
 * ```
 */
export function initMemory(adapter: MemoryAdapter): void {
  currentAdapter = adapter;
  console.log('[Memory] Adapter initialized');
}

/**
 * Get the current MemoryAdapter.
 *
 * @throws if not yet initialized
 */
export function getMemoryAdapter(): MemoryAdapter {
  if (!currentAdapter) {
    throw new Error(
      'Memory not initialized. Call initMemory(adapter) first.\n' +
      'Example: initMemory(createSQLiteAdapter({ dbPath: ":memory:" }))'
    );
  }
  return currentAdapter;
}

/** Check whether the memory system is initialized. */
export function isMemoryInitialized(): boolean {
  return currentAdapter !== null;
}

/** Reset the memory system (mainly for tests). */
export function resetMemory(): void {
  currentAdapter = null;
}
